### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by ydegtyar** [shpp/looking4job#3]
Maybe you missed it, maybe you haven't, but It can be good addition to this page.

**Comment by NastyaSmirnova** [comment]
Any ideas how it can look like? :)

**Comment by ydegtyar** [comment]
@NastyaSmirnova black "J" in yellow box, maybe, good choice until somebody find something better.

**Comment by NastyaSmirnova** [comment]
![image](https://cloud.githubusercontent.com/assets/8417033/21986100/b18da3f2-dc06-11e6-9ac6-7e2b5efb6414.png)
looks aweful on mac

**Comment by ydegtyar** [comment]
Try this http://www.favicon-generator.org/
