### ISSUE TITLE
Add gulp automatization to project

### ISSUE THREAD

**Issue by NastyaSmirnova** [shpp/looking4job#5]
## Requirements:

- [x] gulp serve
- [x] gulp build
- [x] gulp help

**Gulp serve** includes:
- [x] on launch, inject build/l4j.css file to the head section of the index.html
- [x] on .less files changes convert them into one l4j.css file

**Gulp build** includes:
- [x] CSS minification and optimization, save to l4j.min.css
- [x] inject l4j.min.css to head section instead of l4j.css

**Gulp help** includes:
- [x] output all available tasks

_P.S. Don't forget to .ignore node_modules_

**Comment by amativos** [comment]
Use webpack, noobs!
